---
# tasks file for abalage.jellyfin

- name: Create group for Jellyfin
  ansible.builtin.group:
    name: "{{ jellyfin_user }}"
    state: present

- name: Create user for Jellyfin
  ansible.builtin.user:
    name: "{{ jellyfin_user }}"
    create_home: true
    home: "{{ jellyfin_home }}"
    shell: /sbin/nologin
    group: "{{ jellyfin_user }}"
    comment: Dedicated user for Jellyfin
    password: '!'

- name: Download Jellyfin archive
  ansible.builtin.get_url:
    url: "https://repo.jellyfin.org/releases/server/linux/stable/combined/jellyfin_{{ jellyfin_version }}_amd64.tar.gz"
    dest: "{{ jellyfin_home }}/jellyfin_{{ jellyfin_version }}_amd64.tar.gz"
    checksum: "sha256:https://repo.jellyfin.org/releases/server/linux/stable/combined/jellyfin_{{ jellyfin_version }}_amd64.tar.gz.sha256sum"
    mode: 0644

- name: Unarchive downloaded Jellyfin archive
  ansible.builtin.unarchive:
    src: "{{ jellyfin_home }}/jellyfin_{{ jellyfin_version }}_amd64.tar.gz"
    dest: "{{ jellyfin_home }}"
    remote_src: true

- name: Create symlink for Jellyfin
  ansible.builtin.file:
    src: "{{ jellyfin_home }}/jellyfin_{{ jellyfin_version }}"
    dest: "{{ jellyfin_home }}/jellyfin"
    state: link
    owner: "{{ jellyfin_user }}"
    group: "{{ jellyfin_user }}"

- name: Create persistent data directories for Jellyfin instance
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jellyfin_user }}"
    group: "{{ jellyfin_user }}"
    mode: 0755
  loop:
    - "{{ jellyfin_home }}/jellyfin/data"
    - "{{ jellyfin_home }}/jellyfin/cache"
    - "{{ jellyfin_home }}/jellyfin/config"
    - "{{ jellyfin_home }}/jellyfin/log"

- name: Generate script for startup
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ jellyfin_user }}"
    group: "{{ jellyfin_user }}"
    mode: "{{ item.mode }}"
  loop:
    - src: jellyfin.sh.j2
      dest: "{{ jellyfin_home }}/jellyfin.sh"
      mode: '0755'
    - src: jellyfin.service.j2
      dest: "/etc/systemd/system/jellyfin.service"
      mode: '0644'

- name: Start Jellyfin on boot
  ansible.builtin.systemd_service:
    name: jellyfin.service
    daemon_reload: true
    enabled: true
    state: started
  when: jellyfin_autostart
