---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "30 2 * * 0"

defaults:
  run:
    working-directory: ./

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          cd abalage/ansible-role-jellyfin
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - distro: ubuntu2204
            playbook: converge.yml
            experimental: false
          - distro: debian12
            playbook: converge.yml
            experimental: false

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[podman] podman

      - name: Run Molecule tests.
        run: molecule test
        continue-on-error: ${{ matrix.experimental }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}